---
- name: setup puppet agent
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  #become_method: sudo
  hosts: ssl_server
  #hosts: puppet-clients
  #hosts: all
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - { role: ../ansible_role_rsync }
